gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "Fedor$", 13
	.string "Chuvisco$", 13
	.string "Acelerador$", 13
	.string "CouraçaLuta$", 13
	.string "Fortificar$", 13
	.string "Umidade$", 13
	.string "Elasticidade$", 13
	.string "Véu De Areia$", 13
	.string "Estática$", 13
	.string "Absorve Volt$", 13
	.string "Absorve Água$", 13
	.string "Inconsciente$", 13
	.string "Antitempo$", 13
	.string "Olho Preciso$", 13
	.string "Insônia$", 13
	.string "Troca De Cor$", 13
	.string "Imunidade$", 13
	.string "Luz De Fogo$", 13
	.string "Escudo De Pó$", 13
	.string "Rítmo Próprio$", 13
	.string "Braço Sucção$", 13
	.string "Intimidar$", 13
	.string "Fio Sombrio$", 13
	.string "Pele Áspera$", 13
	.string "WONDER GUARD$", 13
	.string "LEVITATE$", 13
	.string "EFFECT SPORE$", 13
	.string "SYNCHRONIZE$", 13
	.string "CLEAR BODY$", 13
	.string "NATURAL CURE$", 13
	.string "LIGHTNINGROD$", 13
	.string "SERENE GRACE$", 13
	.string "SWIFT SWIM$", 13
	.string "CHLOROPHYLL$", 13
	.string "ILLUMINATE$", 13
	.string "TRACE$", 13
	.string "HUGE POWER$", 13
	.string "POISON POINT$", 13
	.string "INNER FOCUS$", 13
	.string "MAGMA ARMOR$", 13
	.string "WATER VEIL$", 13
	.string "MAGNET PULL$", 13
	.string "SOUNDPROOF$", 13
	.string "RAIN DISH$", 13
	.string "SAND STREAM$", 13
	.string "PRESSURE$", 13
	.string "THICK FAT$", 13
	.string "EARLY BIRD$", 13
	.string "FLAME BODY$", 13
	.string "RUN AWAY$", 13
	.string "KEEN EYE$", 13
	.string "HYPER CUTTER$", 13
	.string "PICKUP$", 13
	.string "TRUANT$", 13
	.string "HUSTLE$", 13
	.string "CUTE CHARM$", 13
	.string "PLUS$", 13
	.string "MINUS$", 13
	.string "FORECAST$", 13
	.string "STICKY HOLD$", 13
	.string "SHED SKIN$", 13
	.string "GUTS$", 13
	.string "MARVEL SCALE$", 13
	.string "LIQUID OOZE$", 13
	.string "OVERGROW$", 13
	.string "BLAZE$", 13
	.string "TORRENT$", 13
	.string "SWARM$", 13
	.string "ROCK HEAD$", 13
	.string "DROUGHT$", 13
	.string "ARENA TRAP$", 13
	.string "VITAL SPIRIT$", 13
	.string "WHITE SMOKE$", 13
	.string "PURE POWER$", 13
	.string "SHELL ARMOR$", 13
	.string "CACOPHONY$", 13
	.string "AIR LOCK$", 13
