gMoveNames:: @ 81F8320
	.string "-$$$$$$$", 13
	.string "Tapa$", 13
	.string "Corte Karatê$", 13
	.string "Tapa Duplo$", 13
	.string "Soco Cometa$", 13
	.string "Mega Soco$", 13
	.string "Dia de Pagar$", 13
	.string "Soco de Fogo$", 13
	.string "Soco de Gelo$", 13
	.string "Soco Trovão$", 13
	.string "Arranhão$", 13
	.string "Aderência$", 13
	.string "Guilhotina$", 13
	.string "Lâmina Vento$", 13
	.string "Dança Espada$", 13
	.string "Cortar$", 13
	.string "Ventos$", 13
	.string "Ataque Asas$", 13
	.string "Furacão$", 13
	.string "Voar$", 13
	.string "Enlaçar$", 13
	.string "Pancada$", 13
	.string "Chicote Cipó$", 13
	.string "Pisotear$", 13
	.string "Chute Duplo$", 13
	.string "Mega Chute$", 13
	.string "Voadora$", 13
	.string "Chute Giro$", 13
	.string "Ataque Areia$", 13
	.string "Cabeçada$", 13
	.string "Chifrada$", 13
	.string "Ataque Fúria$", 13
	.string "Broca Chifre$", 13
	.string "Investida$", 13
	.string "Estrondo$", 13
	.string "Enrolar$", 13
	.string "Derrubar$", 13
	.string "Espancamento$", 13
	.string "Dupla Ponta$", 13
	.string "Rabo Chicote$", 13
	.string "Ferroada$", 13
	.string "Agulha Gêmea$", 13
	.string "Míssil Farpa$", 13
	.string "Encarar$", 13
	.string "Mordida", 13
	.string "Rosnar$", 13
	.string "Rugido$", 13
	.string "Canção$", 13
	.string "Supersônico$", 13
	.string "Bomba Sônica$", 13
	.string "Desabilitar$", 13
	.string "Ácido$", 13
	.string "Brasas$", 13
	.string "Lança-Chamas$", 13
	.string "Neblina$", 13
	.string "Jato de Água$", 13
	.string "Hidro Bomba$", 13
	.string "Surfar$", 13
	.string "Raio de Gelo$", 13
	.string "Nevasca$", 13
	.string "Raio Psíquico$", 13
	.string "Rajada Bolha$", 13
	.string "Raio Aurora$", 13
	.string "Hiper Raio$", 13
	.string "Bicada$", 13
	.string "Bico Broca$", 13
	.string "Submissão$", 13
	.string "Rasteira$", 13
	.string "Contra-Ataca$", 13
	.string "Sísmico$", 13
	.string "Força$", 13
	.string "Absorver$", 13
	.string "Megadreno$", 13
	.string "Semente Suga$", 13
	.string "Crescimento$", 13
	.string "Folha Afiada$", 13
	.string "Raio Solar$", 13
	.string "Pó Veneno$", 13
	.string "Pó Atordoa$", 13
	.string "Pó do Sono$", 13
	.string "Dança Pétala$", 13
	.string "Fio de Seda$", 13
	.string "Fúria Dragão$", 13
	.string "Giro de Fogo$", 13
	.string "Choque$", 13
	.string "Raio Trovão$", 13
	.string "Onda Trovão$", 13
	.string "Trovão$", 13
	.string "Lança Rocha$", 13
	.string "Terremoto$", 13
	.string "Ruptura$", 13
	.string "Cavar$", 13
	.string "Tóxico$", 13
	.string "Confusão$", 13
	.string "Psíquico$", 13
	.string "Hipnose$", 13
	.string "Meditação$", 13
	.string "Agilidade$", 13
	.string "Golpe Rápido$", 13
	.string "Raiva$", 13
	.string "Teleporte$", 13
	.string "Sombra Noite$", 13
	.string "Mímica$", 13
	.string "Ruído$", 13
	.string "Time Duplo$", 13
	.string "Recuperar$", 13
	.string "Endurecer$", 13
	.string "Minimizar$", 13
	.string "Tela Fumaça$", 13
	.string "Raio Confuso$", 13
	.string "Retirada$", 13
	.string "Defesa$", 13
	.string "Barreira$", 13
	.string "Tela de Luz$", 13
	.string "Nevoeiro$", 13
	.string "Refletir$", 13
	.string "Focalizar$", 13
	.string "Contra Dano$", 13
	.string "Metrônomo$", 13
	.string "Espelho$", 13
	.string "Autodestrói$", 13
	.string "Bomba de Ovo$", 13
	.string "Lamber$", 13
	.string "Poluição$", 13
	.string "Lodo$", 13
	.string "Taco de Osso$", 13
	.string "Rajada Fogo$", 13
	.string "Cachoeira$", 13
	.string "Prender$", 13
	.string "Ataque Veloz$", 13
	.string "Golpe Cabeça$", 13
	.string "Canhão Farpa$", 13
	.string "Contrair$", 13
	.string "Amnésia$", 13
	.string "Cinese$", 13
	.string "Ovo de Cura$", 13
	.string "Voadora Alta$", 13
	.string "Ofuscar$", 13
	.string "Come Sonho$", 13
	.string "Gás Venenoso$", 13
	.string "Rajada$", 13
	.string "Suga-Vidas$", 13
	.string "Beijo Amável$", 13
	.string "Ataque Aéreo$", 13
	.string "Transformar$", 13
	.string "Bolhas$", 13
	.string "Soco Atordoa$", 13
	.string "Esporos$", 13
	.string "Clarão$", 13
	.string "Psico-Onda$", 13
	.string "Splash$", 13
	.string "Traje Ácido$", 13
	.string "Martelo Crab$", 13
	.string "Explosão$", 13
	.string "Garra Fúria$", 13
	.string "Ossomerangue$", 13
	.string "Descansar$", 13
	.string "Deslizamento$", 13
	.string "Hiper Presa$", 13
	.string "Afiar$", 13
	.string "Conversão$", 13
	.string "Tri Ataque$", 13
	.string "Super Presa$", 13
	.string "Talhada$", 13
	.string "Substituto$", 13
	.string "Insistência$", 13
	.string "Esboço$", 13
	.string "Chute Triplo$", 13
	.string "Ladrão$", 13
	.string "Teia Aranha$", 13
	.string "Ler Mentes$", 13
	.string "Pesadelo$", 13
	.string "Roda De Fogo$", 13
	.string "Roncar$", 13
	.string "Maldição$", 13
	.string "Espancar$", 13
	.string "Conversão 2$", 13
	.string "Explosão Ar$", 13
	.string "Pó Algodão$", 13
	.string "Reversão$", 13
	.string "Rancor$", 13
	.string "Pó de Neve$", 13
	.string "Proteção$", 13
	.string "Soco Rápido$", 13
	.string "Cara Feia$", 13
	.string "Golpe Falso$", 13
	.string "Beijo Doce$", 13
	.string "Tambor$", 13
	.string "Bomba Lodo$", 13
	.string "Tapa de Lama$", 13
	.string "Octazooka$", 13
	.string "Espinhos$", 13
	.string "Canhão Zap$", 13
	.string "Previsão$", 13
	.string "Laço Destino$", 13
	.string "Canto Mortal$", 13
	.string "Vento Gelado$", 13
	.string "Detectar$", 13
	.string "Fúria Ossos$", 13
	.string "Mirar$", 13
	.string "Ultraje$", 13
	.string "Vento Areia$", 13
	.string "Gigadreno$", 13
	.string "Resistência$", 13
	.string "Charme$", 13
	.string "Rolagem$", 13
	.string "Corte Falso$", 13
	.string "Arrogância$", 13
	.string "Beber Leite$", 13
	.string "Faísca$", 13
	.string "Corte Fúria$", 13
	.string "Asa De Ferro$", 13
	.string "Olhar Mal$", 13
	.string "Atração$", 13
	.string "Sonambulismo$", 13
	.string "Sino Da Cura$", 13
	.string "Retorno$", 13
	.string "Presente$", 13
	.string "Frustração$", 13
	.string "Salvaguarda$", 13
	.string "Divide Dor$", 13
	.string "Fogo Sagrado$", 13
	.string "Magnitude$", 13
	.string "Soco Ativo$", 13
	.string "Mega Chifre$", 13
	.string "Bafo Dragão$", 13
	.string "Passa Bastão$", 13
	.string "Repetir$", 13
	.string "Perseguição$", 13
	.string "Giro Rápido$", 13
	.string "Aroma Doce$", 13
	.string "Cauda Ferro$", 13
	.string "Garra Metal$", 13
	.string "Tiro Vital$", 13
	.string "Sol Da Manhã$", 13
	.string "Síntese$", 13
	.string "Luar$", 13
	.string "Poder Oculto$", 13
	.string "Golpe Cruz$", 13
	.string "Ciclone$", 13
	.string "Dança Chuva$", 13
	.string "Dia De Sol$", 13
	.string "Mastigada$", 13
	.string "Capa Espelho$", 13
	.string "Mais Psico$", 13
	.string "Velocidade$", 13
	.string "Poder Antigo$", 13
	.string "Bola Sombria$", 13
	.string "Visão Futura$", 13
	.string "Esmaga Rocha$", 13
	.string "Redemuinho$", 13
	.string "Brigar$", 13
	.string "Surpresa Ruim$", 13
	.string "Uproar$", 13
	.string "Estocagem$", 13
	.string "Liberação$", 13
	.string "Liquido de Cura$", 13
	.string "Onda de Calor$", 13
	.string "Granizo$", 13
	.string "Tormentar$", 13
	.string "Comemorar$", 13
	.string "Laberada$", 13
	.string "Suicídio$", 13
	.string "Fachada$", 13
	.string "Soco Focalizado$", 13
	.string "Sal Mal Cheiroso$", 13
	.string "Siga-me$", 13
	.string "Poder da Natureza$", 13
	.string "Carga$", 13
	.string "Irritação$", 13
	.string "Mão Amiga$", 13
	.string "Truque$", 13
	.string "Troca de Tema$", 13
	.string "Desejo$", 13
	.string "Ajudar$", 13
	.string "Enraizar$", 13
	.string "Super Poder$", 13
	.string "Ataque Mágico$", 13
	.string "Reciclar$", 13
	.string "Vingança$", 13
	.string "Quebra Tijolo$", 13
	.string "Bocejo$", 13
	.string "Nocaute$", 13
	.string "Esforço$", 13
	.string "Erupção$", 13
	.string "Troca Habilidade$", 13
	.string "Imprisão$", 13
	.string "Refrescar$", 13
	.string "Grude$", 13
	.string "Agarrar$", 13
	.string "Poder Secreto$", 13
	.string "Mergulho$", 13
	.string "Golpe de Braço$", 13
	.string "Camuflagem$", 13
	.string "Cauda Brilhante$", 13
	.string "Brilho Purificador$", 13
	.string "Bola da Neblina$", 13
	.string "Dança das Penas$", 13
	.string "Chuva da Confusão$", 13
	.string "Chute Fogo$", 13
	.string "Campo de Lama$", 13
	.string "Bola de Gelo$", 13
	.string "Braço de Agulha$", 13
	.string "Relaxar$", 13
	.string "Hiper Voz$", 13
	.string "Presa Venenosa$", 13
	.string "Garra Esmagadora$", 13
	.string "Explosão Incendiária$", 13
	.string "Hidro Canhão$", 13
	.string "Mistura Meteoro$", 13
	.string "Assustar$", 13
	.string "Bola Climática$", 13
	.string "Terapia Aroma$", 13
	.string "Lágrimas Crocodilo$", 13
	.string "Corte Aéreo$", 13
	.string "Super Aquecer$", 13
	.string "Odor Detectante$", 13
	.string "Tumba de Pedras$", 13
	.string "Vento Prateado$", 13
	.string "Som de Metal$", 13
	.string "Apito de Folha$", 13
	.string "Cócega$", 13
	.string "Poder Cósmico$", 13
	.string "Tromba de Água$", 13
	.string "Raio Sinalizador$", 13
	.string "Soco das Sombras$", 13
	.string "Extra Sensor$", 13
	.string "Soco dos Céus$", 13
	.string "Tombada de Areia$", 13
	.string "Frio Absoluto$", 13
	.string "Mar de Lama$", 13
	.string "Bala de Sementes$", 13
	.string "Ataque Aéreo$", 13
	.string "Lança de Gelo$", 13
	.string "Defesa de Ferro$", 13
	.string "Bloquear$", 13
	.string "Roar$", 13
	.string "Garra do Dragão$", 13
	.string "Planta Mortal$", 13
	.string "Aumentar Massa$", 13
	.string "Ricochetear$", 13
	.string "Rajada Lama$", 13
	.string "Cauda de Veneno$", 13
	.string "Cobiçar$", 13
	.string "Investida Trovão$", 13
	.string "Folha Mágica$", 13
	.string "Campo de Água$", 13
	.string "Mente acalma$", 13
	.string "Lâmina Folha$", 13
	.string "Dança do Dragão$", 13
	.string "Explosão Pedra$", 13
	.string "Onda Choque$", 13
	.string "Pulso da Água$", 13
	.string "Morte Simultânea$", 13
	.string "Aumento Psíquico$", 13
