gNatureName_Hardy: @ 83C0F60
	.string "Ousada$"

gNatureName_Lonely: @ 83C0F66
	.string "Solitária$"

gNatureName_Brave: @ 83C0F6D
	.string "Valente$"

gNatureName_Adamant: @ 83C0F73
	.string "Inflexível$"

gNatureName_Naughty: @ 83C0F7B
	.string "Travessa$"

gNatureName_Bold: @ 83C0F83
	.string "Audaciosa$"

gNatureName_Docile: @ 83C0F88
	.string "Dócil$"

gNatureName_Relaxed: @ 83C0F8F
	.string "Descontraída$"

gNatureName_Impish: @ 83C0F97
	.string "Transtornada$"

gNatureName_Lax: @ 83C0F9E
	.string "Relaxada$"

gNatureName_Timid: @ 83C0FA2
	.string "Tímida$"

gNatureName_Hasty: @ 83C0FA8
	.string "Apressada$"

gNatureName_Serious: @ 83C0FAE
	.string "Séria$"

gNatureName_Jolly: @ 83C0FB6
	.string "Alegre$"

gNatureName_Naive: @ 83C0FBC
	.string "Ingênua$"

gNatureName_Modest: @ 83C0FC2
	.string "Modesta$"

gNatureName_Mild: @ 83C0FC9
	.string "Branda$"

gNatureName_Quiet: @ 83C0FCE
	.string "Quieta$"

gNatureName_Bashful: @ 83C0FD4
	.string "Envergonhada$"

gNatureName_Rash: @ 83C0FDC
	.string "Precipitada$"

gNatureName_Calm: @ 83C0FE1
	.string "Calma$"

gNatureName_Gentle: @ 83C0FE6
	.string "Gentil$"

gNatureName_Sassy: @ 83C0FED
	.string "Descarada$"

gNatureName_Careful: @ 83C0FF3
	.string "Cuidadosa$"

gNatureName_Quirky: @ 83C0FFB
	.string "Peculiar$"

	.align 2
gNatureNames:: @ 83C1004
	.4byte gNatureName_Hardy
	.4byte gNatureName_Lonely
	.4byte gNatureName_Brave
	.4byte gNatureName_Adamant
	.4byte gNatureName_Naughty
	.4byte gNatureName_Bold
	.4byte gNatureName_Docile
	.4byte gNatureName_Relaxed
	.4byte gNatureName_Impish
	.4byte gNatureName_Lax
	.4byte gNatureName_Timid
	.4byte gNatureName_Hasty
	.4byte gNatureName_Serious
	.4byte gNatureName_Jolly
	.4byte gNatureName_Naive
	.4byte gNatureName_Modest
	.4byte gNatureName_Mild
	.4byte gNatureName_Quiet
	.4byte gNatureName_Bashful
	.4byte gNatureName_Rash
	.4byte gNatureName_Calm
	.4byte gNatureName_Gentle
	.4byte gNatureName_Sassy
	.4byte gNatureName_Careful
	.4byte gNatureName_Quirky
