UnknownString_8173A9D: @ 8173A9D
	.string "ESPÉCIES E HABITAR DE POKÉMONS...\n"
	.string "COEXISTÊNCIA HUMANA E POKÉMON...\l"
	.string "POKÉMONOLOGIA PARA INICIADORES...\p"
	.string "Está repleto de livros escritos pelo\n"
	.string "professor Birch.$"

LittlerootTown_ProfessorBirchsLab_Text_173B29:: @ 8173B29
	.string "Hunh? Professor Brich?\p"
     .string "O professor saiu para estudar no campo\n"
     .string "Ergo, ele não está aqui.\p"
     .string "Oh, deixe-me explicar o que é o trabalho de campo.\p"
     .string "É estudar coisas no ambiente natural\n"
     .string", como campos e montanha,\l "
     .string "em vez de um laboratório.\p"
     .string "O professor não é um para fazer trabalhos de mesa.\n"
     .string "Ele é o tipo de pessoa que iria"
     .string "prefere sair e experimentar\l"
     .string "coisas que lidas sobre eles aqui.$"

LittlerootTown_ProfessorBirchsLab_Text_173C88 :: @ 8173C88
     .string "O professor não é um para fazer trabalhos de mesa.\n"
     .string "Ele é o tipo de pessoa que iria\n"
     .string "prefere sair e experimentar\l"
     .string "coisas que lidas sobre eles aqui.$"

LittlerootTown_ProfessorBirchLab_Text_173D15 :: @ 8173D15
     .string "Professor Birch está estudando os habitats\n"
     .string "e distribuição de POKéMON.\p"
     .string "O professor desfruta também da ajuda do {RIVAL}.\n"
     .string "Há muito amor lá.$"

LittlerootTown_ProfessorBirchsLab_Text_173D94 :: @ 8173D94
     .string "Professor Birch: Então, {PLAYER} {KUN}.\p"
     .string "Eu já ouvi falar sobre você de\n"
     .string "seu pai.\p"
     .string "Eu ouvi dizer que você não tem o seu\n"
     .string "próprio POKéMON ainda.\p"
     .string "Mas a maneira como você lutou anteriormente,\n"
     .string " você puxou-o com aplomo! \ p"
     .string "Eu acho que você tem o sangue do seu pai\n"
     .string "em suas veias depois de tudo!\p"
     .string "Oh, sim. Como obrigado por me resgatar,\n"
     .string "Eu gostaria que você tivesse o POKéMON você\l"
     .string "usado anteriormente.\p"
     .string "{PLAYER} recebeu o {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_173EF8 :: @ 8173EF8
     .string "Professor Birch: Enquanto você está nisso, por que não\n"
     .string "dê um apelido para o {STR_VAR_1}?$"

LittlerootTown_ProfessorBirchsLab_Text_173F3D :: @ 8173F3D
     .string "Professor Birch: Se você trabalha com seu POKéMON\n"
     .string "e ganhar experiência, acho que você será\l"
     .string "um bom treinador.\p"
     .string "Minha filha, {RIVAL}, está na ROTA 103\n"
     .string "estudando POKéMON. \ p"
     .string "Talvez não seja uma má idéia para você\n"
     .string "vá ver {RIVAL}. O que você acha?$"

LittlerootTown_ProfessorBirchsLab_Text_174015 :: @ 8174015
     .string "Professor Birch: Ótimo!\n"
     .string "{RIVAL} também deve ser feliz.\p"
     .string "Obter um RIVAL para ensinar o que\n"
     .string "significa ser um TREINADOR.$"

LittlerootTown_ProfessorBirchsLab_Text_174075 :: @ 8174075
     .string "Professor Birch: Oh, não seja assim.\n"
     .string "Você deve ir até {RIVAL}!$"

LittlerootTown_ProfessorBirchsLab_Text_1740B4:: @ 81740B4
	.string "Professor Birch: {RIVAL} deve estar em\n"
	.string "ROTA 103 em algum lugar.\p"
	.string "Se você ou seu POKéMON ficarem cansados,\n"
	.string " descance em casa.$"

LittlerootTown_ProfessorBirchsLab_Text_17411F:: @ 817411F
	.string "Professor Birch: Oh, oi, {PLAYER}{KUN}!\p"
	.string "Eu ouvi dizer que você ganhou de {RIVAL} em\n"
	.string "sua primeira batalha. Bacana!\p"
	.string "{RIVAL} me ajudou na pesquisa\n"
	.string "num longo tempo.\p"
	.string "{RIVAL} tem uma extensa história como\n"
	.string "um TREINADOR.\p"
	.string "Aqui, {PLAYER}{KUN}, eu pedi isso aqui para meu\n"
	.string "ajudante, mas acho que você deveria\l"
	.string "ter a POKéDEX.$"

LittlerootTown_ProfessorBirchsLab_Text_17422F:: @ 817422F
	.string "{PLAYER} recebeu a POKéDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_174248:: @ 8174248
	.string "Professor Birch: O POKéDEX e uma alta tecnológica\n"
	.string "que faz automaticamente uma gravação\l"
	.string "de qualquer POKÉMON que você veja ou captura.\p"
	.string "Meu filho, {RIVAL}, vai em todo lugar\n"
	.string "com ele.\p"
	.string "Sempre que meu filho pegue um POKéMON raro\n"
	.string "ele registra os dados nele com a POKéDEX,\l"
	.string "porque, {RIVAL} procura-me quando estou fora\l"
	.string "fazendo trabalho de campo, e me mostra.$"

LittlerootTown_ProfessorBirchLab_Text_17436C:: @ 817436C
	.string "Professor Birch: inúmeros POKéMON aguardam\n"
	.string "você!\p"
	.string "Argh, estou recebendo um chamado para sair\n"
	.string "para fazer trabalho de campo novamente!$"

LittlerootTown_ProfessorBirchLab_Text_1743D4:: @ 81743D4
	.string "May: Oh, uau, {PLAYER}{KUN}!\n"
	.string "você recebeu a POKéDEX, também!\p"
	.string "Que bom! Assim como eu!\n"
	.string "Eu também tenho algo para você!$"

LittlerootTown_ProfessorBirchsLab_Text_17443D:: @ 817443D
	.string "May: O mais divertido é capturar muitos\n"
	.string "POKéMON!\p"
	.string "Eu vou olhar em diferentes lugares\n"
	.string "Pois eu quero diferentes POKéMON.\p"
	.string "Se eu encontrar qualquer POKéMON bonito,\n"
	.string " vou pegar,pois tenho POKÉBOLAS!$"

LittlerootTown_ProfessorBirchsLab_Text_1744F0:: @ 81744F0
	.string "Oh? Sua mochila está cheia.$"

LittlerootTown_ProfessorBirchsLab_Text_174505:: @ 8174505
	.string "May: Eu me pergunto onde deveria olhar\n"
	.string "um POKéMON depois?$"

LittlerootTown_ProfessorBirchsLab_Text_17453C:: @ 817453C
	.string "Brendan: Huh...\n"
	.string "Você tem a POKéDEX, também.\p"
	.string "Bem então, aqui.\n"
	.string "Vou te dar isso.$"

LittlerootTown_ProfessorBirchsLab_Text_17458C:: @ 817458C
	.string "Brendan: Você sabe o que é mais divertido\n"
	.string "ter muitos POKéMON.\p"
	.string "Eu vou explorar todo lugar\n"
	.string "para encontrar diferentes POKéMON.\p"
	.string "Se eu encontrar um POKéMON legal,\n"
	.string " vou pega-lo com POKéBALLS.$"

LittlerootTown_ProfessorBirchsLab_Text_17465B:: @ 817465B
	.string "Hey, sua mochila está cheia.$"

LittlerootTown_ProfessorBirchsLab_Text_174671:: @ 8174671
	.string "BRENDAN: Onde devo procurar um\n"
	.string "um POKéMON seguinte...$"

LittlerootTown_ProfessorBirchsLab_Text_1746A2:: @ 81746A2
	.string "É uma maquina séria.\n"
	.string "O professor deve usar pra pesquisar .$"

LittlerootTown_ProfessorBirchsLab_Text_1746E7:: @ 81746E7
	.string "É um PC usado para pesquisa.\n"
	.string "Melhor não mexer nisso.$"

LittlerootTown_ProfessorBirchsLab_Text_174724:: @ 8174724
	.string "São livros sobre  POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_174748:: @ 8174748
	.string "É um livro difícil de ler.$"
