LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "Mãe: {PLAYER}, chegamos, meu bem!\p"
	.string "deve ser cansativo viajar com nossas coisas\n"
	.string "no caminhão em movimento.\p"
	.string "Bem, aqui é Littleroot Town.\p"
	.string "Você gostou?\n"
	.string "Essa é nossa nova casa!\p"
	.string "Tem uma sensação peculiar, mas parecer ser\n"
	.string "um lugar fácil de viver, não acha?\p"
	.string "E, você tem seu próprio quarto, {PLAYER}!\n"
	.string "vamos entrar.$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "Mãe: Espera, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "Mãe: {PLAYER}! {PLAYER}! Você se\n"
	.string "apresentou ao Prof. Birch?\p"
	.string "Oh! Que pokémon adorável\n"
	.string "Você obteve do Prof. Birch. Que bacana!\p"
	.string "Você é filho do seu pai, tudo bem.\n"
	.string "Você parece bem com seu pokémon!\p"
	.string "Aqui meu bem! se você estiver saindo em uma\n"
	.string "aventura, use estes sapatos de corrida.\p"
	.string "Eles irão ajudar na aventura!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER} trocou os sapatos por\n"
	.string "sapatos de corrida.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "Mãe: {PLAYER}, esses sapatos vieram com\n"
	.string "instruções.\p"
	.string "“Pressione o botão B enquanto estiver com eles\n"
	.string "para correr rápido!\p"
	.string "“Vá com estes sapatos de corrida\n"
	.string "e corra ao ar livre!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "E pensar que você tem seu próprio\n"
	.string "pokémon agora...\l"
	.string "Seu pai ficará feliz.\p"
	.string "...Mas seja cuidadoso.\n"
	.string "Se algo acontecer, pode voltar para casa.\p"
	.string "Capture todos, meu bem!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "Se você usar o PC, você poderá armazenar itens\n"
	.string "e pokémon.\p"
	.string "O poder da ciência é surpreendente!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "Prof. Birch passa dias no seu laboratório\n"
	.string "estudando, e derrepente ele sai para\l"
	.string "a selva fazer pesquisa...\p"
	.string "Quando o Prof. Birch\n"
	.string "ficam em casa?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Se você passar na grama alta\n"
	.string "nessa estrada, um pokémon selvagem aparecerá.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "Não é seguro ir para a estrada\n"
	.string "se você não possuir pokémon.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Posso ouvir alguém gritando\n"
	.string "nessa estrada.\p"
	.string "O que faço? O que devemos fazer?\n"
	.string "Alguém tem que ajudar...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Nossa, estou tão feliz por você\n"
	.string "ajudado o professor.$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Você vai capturar pokémon?\n"
	.string "Boa sorte!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "Littleroot Town\n"
	.string "“Uma cidade que não pode ser sombreada.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "Laboratório do Prof. Birch$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "Casa do{PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "Casa do Prof. Birch$"
