LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "Mãe: {PLAYER}, chegamos!\p"
	.string "Deve ser cansativo viajar com nossas\n"
	.string "coisas balançando no caminhão.\p"
	.string "Bem, aqui é Littleroot Town.\p"
	.string "Você gostou?\n"
	.string "Essa é nossa nova casa!\p"
	.string "Tem uma sensação peculiar, mas parece\n"
	.string "ser um lugar fácil de viver, não acha?\p"
	.string "Agora, você tem seu próprio quarto.\n"
	.string "Vamos entrar.$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "Mãe: Espera, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "Mãe: {PLAYER}! {PLAYER}! Você se\n"
	.string "apresentou ao Professor Birch?\p"
	.string "Olha! Que pokémon adorável.\n"
	.string "Você obteve do Professor Birch?\p"
	.string "Você é parece com o seu pai.\n"
	.string "Seu pokémon parece bem com você.\p"
	.string "Leve isso com você! Quando sair para\n"
	.string "uma aventura, você poderá correr.\p"
	.string "Espero que ajude em sua aventura.$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER} trocou os sapatos por\n"
	.string "sapatos de corrida.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "Mãe: {PLAYER}, esses sapatos vieram\n"
	.string "com instruções.\p"
	.string "“Segure o botão B enquanto\n"
	.string "estiver com eles para correr.\p"
	.string "Aproveite os sapatos de corrida\n"
	.string "e corra ao ar livre!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "E pensar que você tem seu próprio\n"
	.string "pokémon agora...\l"
	.string "Seu pai ficará muito feliz.\p"
	.string "... Mas seja cuidadoso.\n"
	.string "Se algo acontecer, pode voltar\l"
	.string "para casa.\p"
	.string "Capture todos e se cuide!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "Se você usar o computador, poderá\n"
	.string "armazenar itens e pokémon.\p"
	.string "O poder da ciência é surpreendente!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "O Professor Birch passa dias no seu\n"
	.string "laboratório estudando, às vezes, ele\l"
	.string "sai na selva para pesquisar...\p"
	.string "Quando o Professor Birch passa algum\n"
	.string "tempo em casa?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Se você passar pela grama alta, um\n"
	.string "pokémon selvagem poderá te atacar.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "É perigos ir para essa rota se você\n"
	.string "não possuir pokémon.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Alguém está gritando nessa rota.\p"
	.string "O que faço? O que devemos fazer?\n"
	.string "Alguém tem que ajudar...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Nossa, estou tão feliz por você ter\n"
	.string "ajudado o professor.$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Você vai capturar pokémon?\n"
	.string "Boa sorte!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "Littleroot Town\n"
	.string "“A cidade que não pode ser sombreada.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "Laboratório do Professor Birch$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "Casa do {PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "Casa do Professor Birch$"
